### ISSUE TITLE
Images in annotations boxes are not scaled to fit

### ISSUE THREAD

**Issue by villedigirati** [digirati-co-uk/iiif-manifest-editor-components#17]

**Comment by villedigirati** [comment]
Couldnt add images - the form has changed?

**Comment by adam-digirati** [comment]
Yes, Angela asked to instead of inline base 64 encoded images they would use image URL, therefore I updated the way you specify an image. Instead of an file selector it displays a filed where the user can put the image location. 

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/33420570/55187585-57ffcb00-5191-11e9-8186-aef03bdc27df.gif)

Same applies for the videos.
